---
- name: "Check secrets file."
  ansible.builtin.stat:
    path: "{{ options.proxmox_secrets }}"
  register: proxmox_secrets_st

- name: "Fail if secrets file not found."
  ansible.builtin.fail:
    msg: "proxmox_secrets not found: {{ options.proxmox_secrets }}"
  when: not proxmox_secrets_st.stat.exists

- name: "Load proxmox secrets from file."
  ansible.builtin.include_vars: "{{ options.proxmox_secrets }}"
  when: not proxmox_secrets_st.stat.executable
  no_log: "{{ not (options.debug | d(False) | bool) }}"

- name: "Load promox secrets from executable output."
  when: proxmox_secrets_st.stat.executable
  no_log: "{{ not (options.debug | d(False) | bool) }}"
  block:
    - name: "Run proxmox secrets script."
      ansible.builtin.command: "{{ options.proxmox_secrets }}"
      changed_when: false
      register: proxmox_secrets_cmd

    - name: "Load proxmox secrets from script output."
      vars:
        secrets: "{{ proxmox_secrets_cmd.stdout | from_yaml }}"
      ansible.builtin.set_fact:
        "{{ item }}": "{{ secrets[item] }}"
      with_items: "{{ secrets.keys() }}"
