---
- name: "Stat proxmox secrets file."
  ansible.builtin.stat:
    path: "{{ options.proxmox_secrets }}"
    get_checksum: no
  register: st

- name: "Verify proxmox secret file exists."
  ansible.builtin.fail:
    msg: "proxmox_secrets file {{ options.proxmox_secrets }} not found."
  when: not st.stat.exists

- name: "Load proxmox secrets."
  ansible.builtin.include_vars: "{{ options.proxmox_secrets }}"
  no_log: true
